### ISSUE TITLE
Header Menu layout configuration suggestion

### ISSUE THREAD

**Issue by TetraTheta** [hbstack/header#308]
I think recent update(s) have broken header menu layout. Here are my opinions.

![1](https://github.com/hbstack/header/assets/37061801/1f414337-c50b-4b3b-9852-a89b935cb38b)

If there are only one child menu like this, the menu should not have two columns. One column is enough for this situation.

![2](https://github.com/hbstack/header/assets/37061801/aa6e068f-1732-4e49-afc6-244f339f5c63)

To me, this layout looks 'unorganized'. I'd prefer layout like this (poorly edited though)

![4](https://github.com/hbstack/header/assets/37061801/589bed5c-9e81-4854-a24c-16c7d9f7b8fd)

First colume would be 'primary column'. If its child menu's count is odd number, first column should have one more menu than second column.

Also top-level menu description should have full length, rather than having same length with its child menu items.

Speaking of top-level menu description, I've found that it is already addressed in 1c123193a1a0ad74a3cb984eedbc7dc35ea89e4d and it is released as [v0.10.1](https://github.com/hbstack/header/releases/tag/v0.10.1) but it doesn't get updated to this version if I run `hugo mod get -u` command. Maybe I should manually set its version to v0.10.1...

---

And I wish there is an option for this, like 'How many columns that the menu have?'

It can be look like this:
```yaml
main:
  - name: Chit Chat
    identifier: chit-chat
    weight: 1
    url: /chit-chat
    params:
      header: Chit Chat
      description: Chit Chat
      # column determins how many colume that this top-level menu would have
      column: 2
      icon:
        vendor: font-awesome-solid
        name: message
```
This will provide user more freedom of how the menu look like.

For example in this layout, if we have `column: 3` and its child menu's count is `8`, first and second column would have 3 menus, and last colum would have 2 menus.
