### ISSUE TITLE
`columns` parameter doesn't work?

### ISSUE THREAD

**Issue by FuadEfendi** [hbstack/header#622]
I have "dictionary" with letters A-Z as submenu, which by default uses 2 columns in menu. I tried to make it 4 columns, but it instead becomes 1 column. Tested with 1 and 2, it works as expected, but when I set `columns: 3` it shows single column only:

```
---
title: Dictionary
menu:
  main:
    identifier: dictionary
    weight: 4
    params:
      columns: 2
      icon:
        vendor: fas
        name: blog
---
```

UPDATE: sorry I just noticed, it is not a bug as per documentation,
> The column count of sub menus, **up to 2,** default to 1 when the number of menus is less than 6, otherwise 2.

https://hbstack.dev/modules/header/menus/
